version: '3.8'

services:
  jirella-farm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3023:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - jnet

networks:
  jnet:
    external: true