version: '3.8'

services:
  jirella-farm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3023:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=http://65.21.2.74:54321
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzcwMTk5NTY4LCJleHAiOjE5Mjc4Nzk1Njh9.6FVcFgXRpDc8V_oFpZoDuggvJQKfm_V17IMkL3Jtero
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NzAxOTk1NjgsImV4cCI6MTkyNzg3OTU2OH0.O2TGZ1gDAdS2Dmj1GhMIWKWwePAhTv2yWbEV2XlX6zU
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - jnet

networks:
  jnet:
    external: true